FROM redjays/xenial:latest
MAINTAINER RJ <rbergero@gmail.com>
RUN env LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get install -q -y linux-image-generic linux-headers-generic dkms
RUN usermod -p '$6$rxisUuge$gLqvQTkeY3zcM7mg/Di7T7SmLAAyRvGOJS9h31zxz79viBN1Y2dqJKc30bb31mwkstJPwDRxcK/O.AU77zEii/' root
