#!/bin/bash

# base xen boot arguments
if [ "$(nproc)" -gt 4 ] ; then
  cpumax="4"
else
  cpumax="1"
fi

memtot=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
if [ "${memtot}" -ge 32961732 ] ; then # 32G+
  memmax="8G"
elif [ "${memtot}" -ge 16184516 ] ; then # 16G+
  memmax="3G"
elif [ "${memtot}" -ge 7795908 ] ; then # 8G+
  memmax="1G"
else
  memmax="384M"
fi

xen_cmdline="dom0_max_vcpus=${cpumax} dom0_mem=${memmax} allow_unsafe"

# figure out serial console by asking grub what _it_ does
grub_term=$(augtool print /files/etc/default/grub/GRUB_TERMINAL)
grub_term="${grub_term#* = }"

case "${grub_term}" in
  *serial*)
    grub_sercmd=$(augtool print /files/etc/default/grub/GRUB_SERIAL_COMMAND)
    grub_sercmd="${grub_sercmd#* = }"
    for param in ${grub_sercmd} ; do
      case "${param}" in
        --unit=*)
          CONFIG_SERIAL_INSTALL=${param#--unit=}
          # xen uses com1, com2...as opposed to ttyS0 for linux/grub
          xen_com=$((CONFIG_SERIAL_INSTALL + 1))
          xen_cmdline="${xen_cmdline} com${xen_com}=115200,8n1 console=com${xen_com}"
          ;;
      esac
    done
    ;;
esac

# adapt the grub linux boot options for the grub linux/xen boot options
lx_def_cmdline=$(augtool print /files/etc/default/grub/GRUB_CMDLINE_LINUX_DEFAULT)
lx_def_cmdline="${lx_def_cmdline#* = }"
lx_def_cmdline="${lx_def_cmdline:3:-3}"
lx_xe_def_cmdline='console=hvc0 earlyprintk=xenboot'
for arg in ${lx_def_cmdline} ; do
  case "${arg}" in
    console=*)
      :
      ;;
    *)
      lx_xe_def_cmdline="${lx_xe_def_cmdline} ${arg}"
      ;;
  esac
done

# quotes and backticks for augtool hell
xen_cmdline=\"\\\""${xen_cmdline}"\\\"\"
lx_xe_def_cmdline=\"\\\""${lx_xe_def_cmdline}"\\\"\"

augtool -s set /files/etc/default/grub/XEN_OVERRIDE_GRUB_DEFAULT 1
augtool -s set /files/etc/default/grub/GRUB_CMDLINE_XEN "${xen_cmdline}"
augtool -s set /files/etc/default/grub/GRUB_CMDLINE_LINUX_XEN_REPLACE_DEFAULT "${lx_xe_def_cmdline}"
