#!/bin/bash

# No point in trying this if we don't have mdraid
which mdraid >/dev/null 2>&1 || exit 1

. "$dracutfunctions"
[[ $debug ]] && set -x

# if there is no mdraid using fio, go away
fiomds=(/sys/block/md*/slaves/fio*)
if [ -z "${fiomds[0]}" ] ; then exit 1 ; fi

exit 0
